"""Publication metadata, topic definitions, and legacy copy normalization."""

import re

DEFAULT_EPI_DOSSIER_REPO = "https://github.com/dteichrow/epi-dossier.git"
PUBLIC_SITE_ORIGIN = "https://devinteichrow.com"
PUBLIC_SITE_DOMAIN = "devinteichrow.com"
DEFAULT_SOCIAL_IMAGE = (
    "assets/substack-brand/edge-of-epidemiology-email-banner-1100x220.png"
)
RSS_FEED_URL = "https://theedgeofepidemiology.substack.com/feed"
AUTHOR_SAME_AS = [
    "https://theedgeofepidemiology.substack.com",
    "https://x.com/edgeofepi",
    "https://www.instagram.com/edgeofepi/",
    "https://www.linkedin.com/in/devin-teichrow-msc-938942254",
    "https://medium.com/@EdgeofEpi",
]
# Legacy records can still carry `noindex_stub`; it is normalized to `summary_only` below.
# Only explicit private or draft markers block indexing now.
NOINDEX_POST_STRATEGIES = {
    "noindex",
    "noindex_stub_private",
    "private",
    "draft",
    "hidden",
}
DOI_URL_PATTERN = re.compile(r"(^|/)(10\.[0-9]{4,9}/\S+)", re.IGNORECASE)
GENERIC_DESCRIPTIONS = {
    "",
    "About Edge of Epidemiology.",
    "Edge of Epidemiology publication page.",
    "Source-first outbreak reporting from The Pathogen Dispatch.",
    "Interactive atlas from The Edge of Epidemiology.",
}
TOPIC_HUBS = [
    {
        "slug": "historical-epidemiology",
        "title": "Historical Epidemiology",
        "description": "Essays on epidemics as historical forces: ancient pathogens, colonial encounters, disease ecology, and the long memory of public health.",
        "keywords": [
            "history",
            "historical epidemiology",
            "ancient",
            "colonial",
            "plague",
            "cocoliztli",
            "syphilis",
        ],
    },
    {
        "slug": "disease-and-war",
        "title": "Disease And War",
        "description": "War, armies, migration, logistics, barracks, ships, and the infections that move through military systems.",
        "keywords": [
            "war",
            "military",
            "revolutionary",
            "korean",
            "napoleon",
            "soldier",
            "oregon trail",
        ],
    },
    {
        "slug": "disease-ecology",
        "title": "Disease Ecology",
        "description": "Disease stories where landscapes, reservoirs, vectors, cities, climate, and infrastructure explain more than the pathogen alone.",
        "keywords": [
            "ecology",
            "vector",
            "mosquito",
            "climate",
            "environment",
            "raw milk",
            "zoonotic",
        ],
    },
    {
        "slug": "pathogen-geography",
        "title": "Pathogen Geography",
        "description": "Map-first work on how pathogens travel through ports, ships, animal reservoirs, water systems, roads, empires, and borders.",
        "keywords": [
            "atlas",
            "geography",
            "pathogen",
            "maritime",
            "ship",
            "route",
            "port",
        ],
    },
    {
        "slug": "epidemiologic-methods",
        "title": "Epidemiologic Methods",
        "description": "Readable epidemiology methods, causal inference, risk communication, evidence grading, replication, and statistical thinking.",
        "keywords": [
            "causal",
            "risk",
            "evidence",
            "baseline",
            "replication",
            "wearable",
            "meta-analysis",
            "studies",
        ],
    },
    {
        "slug": "wellness-claims",
        "title": "Wellness Claims",
        "description": "Evidence-first writing on supplements, nutrition, wellness panics, influencer claims, and health stories that outrun the data.",
        "keywords": [
            "wellness",
            "supplement",
            "raw milk",
            "gluten",
            "creatine",
            "melatonin",
            "detox",
            "sweetener",
            "dopamine",
        ],
    },
    {
        "slug": "neuroepidemiology",
        "title": "Neuroepidemiology",
        "description": "Neuroepidemiology essays on migraine, cognition, epilepsy, dementia, Parkinson's disease, multiple sclerosis, and brain-health evidence.",
        "keywords": [
            "migraine",
            "brain",
            "neuro",
            "alzheimer",
            "parkinson",
            "epilepsy",
            "seizure",
            "cognition",
            "ms",
        ],
    },
]
PATHOGEN_ATLAS_COLORS = {
    "variola-smallpox": "#b56b5b",
    "yersinia-pestis-plague": "#b9754f",
    "vibrio-cholerae-cholera": "#5a9bd4",
    "mycobacterium-tuberculosis-complex": "#d98e5f",
    "influenza-a": "#b7c7df",
    "measles-virus": "#d6c06a",
    "yellow-fever-virus": "#d86a4f",
    "dengue-virus": "#c9a84c",
    "malaria-parasites": "#bb9cdb",
    "hantaviruses": "#c99a73",
    "hiv-1": "#d26b91",
    "sars-cov-2": "#7b8fa8",
    "poliovirus": "#7c9fd1",
    "treponema-pallidum-syphilis": "#c38a65",
    "salmonella-enterica": "#bc8f5f",
    "rickettsia-prowazekii-epidemic-typhus": "#9a8c5f",
    "yellow-fever": "#d86a4f",
    "cholera": "#5a9bd4",
    "measles": "#d6c06a",
    "mpox": "#dd6974",
    "avian-influenza-h5n1": "#9b7bd8",
    "hantavirus": "#c99a73",
    "dengue": "#c9a84c",
    "malaria": "#bb9cdb",
    "tuberculosis": "#d98e5f",
    "plague": "#b9754f",
    "zika-virus-disease": "#6a6fab",
    "chikungunya": "#d9a441",
    "west-nile-virus": "#7075ae",
    "japanese-encephalitis": "#6fa8dc",
    "poliomyelitis": "#7c9fd1",
    "hepatitis-a": "#c9b56b",
    "typhoid-fever": "#bc8f5f",
    "norovirus": "#6b70a3",
    "smallpox": "#b56b5b",
    "seasonal-influenza": "#b7c7df",
    "covid-19": "#7b8fa8",
    "ebola-virus-disease": "#b84646",
    "marburg-virus-disease": "#9f3f43",
    "nipah-virus-disease": "#7a6f4f",
    "lassa-fever": "#b17d5a",
    "rabies": "#9c6f3d",
    "anthrax": "#8c7a55",
    "mers": "#b88a55",
    "diphtheria": "#5a609c",
    "pertussis": "#c7a05a",
    "lyme-disease": "#6f739f",
    "rocky-mountain-spotted-fever": "#c07b4f",
    "crimean-congo-hemorrhagic-fever": "#b04f63",
    "epidemic-typhus": "#b38a5a",
    "murine-typhus": "#9a7d55",
    "scrub-typhus": "#5a60a0",
    "salmonellosis": "#c6a15a",
    "listeriosis": "#7a7eae",
    "botulism": "#8d7868",
    "tetanus": "#a88d5d",
    "melioidosis": "#5f649c",
    "coccidioidomycosis": "#c28f5a",
    "hiv-aids": "#9d5f7a",
    "hepatitis-b": "#b6974f",
    "syphilis": "#aa6a58",
    "leishmaniasis": "#d0a24a",
    "chagas-disease": "#9f6b4d",
    "onchocerciasis": "#6d719b",
    "clostridioides-difficile-infection": "#787b9f",
    "mrsa-infection": "#9c6d70",
    "tick-borne-encephalitis": "#62668f",
    "anaplasmosis": "#6c709b",
    "ehrlichiosis": "#a27858",
    "babesiosis": "#717497",
    "shigellosis": "#b16f58",
    "rotavirus": "#c5a65b",
    "giardiasis": "#6f739f",
    "cryptosporidiosis": "#656a9f",
    "amebiasis": "#a47b54",
    "campylobacteriosis": "#bd8b4d",
    "yersiniosis": "#9b815d",
    "shiga-toxin-producing-e-coli-infection": "#b57456",
    "rubella": "#c27c8a",
    "mumps": "#9c83b7",
    "varicella": "#7c9bc6",
    "brucellosis": "#b18a52",
    "leptospirosis": "#6f739b",
    "q-fever": "#a8835a",
    "carbapenem-resistant-enterobacterales-infection": "#8f7668",
    "vancomycin-resistant-enterococcus-infection": "#806f8f",
    "rift-valley-fever": "#b88742",
    "eastern-equine-encephalitis": "#575d9c",
    "la-crosse-encephalitis": "#6d719c",
    "lymphatic-filariasis": "#a7a75a",
    "ross-river-virus-disease": "#5e639f",
    "oropouche-virus-disease": "#c39a4e",
    "lymphocytic-choriomeningitis": "#8f7a54",
    "rat-bite-fever": "#9b705d",
    "tularemia": "#62679b",
    "histoplasmosis": "#a98355",
    "blastomycosis": "#8f875e",
    "aspergillosis": "#6f728f",
    "sporotrichosis": "#b07d58",
    "gonorrhea": "#a86770",
    "chlamydia": "#c08a67",
    "genital-herpes": "#9b6c94",
    "acinetobacter-infection": "#756f8c",
    "pseudomonas-aeruginosa-infection": "#5f649b",
    "vibriosis": "#5b9fb6",
    "trichinellosis": "#b18f55",
    "respiratory-syncytial-virus-infection": "#9bb3c8",
    "meningococcal-disease": "#8a9ab6",
    "pneumococcal-disease": "#b28d6b",
    "haemophilus-influenzae-type-b-disease": "#9c8fb8",
    "legionnaires-disease": "#5f649f",
    "candida-auris-infection": "#c08a5d",
    "invasive-candidiasis": "#a77c68",
    "human-papillomavirus-infection": "#b06d93",
    "hepatitis-c": "#c49a57",
    "scabies": "#a88957",
    "leprosy": "#9c7d68",
    "cyclosporiasis": "#6c709f",
    "dracunculiasis": "#b5a45b",
    "schistosomiasis": "#6f74a6",
    "ascariasis": "#9f875b",
    "hookworm-disease": "#8f7b55",
    "toxoplasmosis": "#967ab0",
    "psittacosis": "#6f7296",
    "human-african-trypanosomiasis": "#b59a52",
    "echinococcosis": "#8e8f5e",
    "adenovirus-infection": "#8fa4b8",
    "human-parainfluenza-virus-infection": "#9eb5c2",
    "mycoplasma-pneumoniae-infection": "#b18f6f",
    "group-a-streptococcal-disease": "#b0786a",
    "hand-foot-and-mouth-disease": "#b69a54",
    "hepatitis-d": "#a78352",
    "hepatitis-e": "#c39b59",
    "cysticercosis": "#9f8f61",
    "clonorchiasis": "#666b9f",
    "fascioliasis": "#585e9b",
    "paragonimiasis": "#9f7a54",
    "anisakiasis": "#6167a6",
    "strongyloidiasis": "#8e7d57",
    "toxocariasis": "#9a865b",
    "baylisascariasis": "#8c705f",
    "loiasis": "#b79b52",
    "group-b-streptococcal-disease": "#9f7a84",
    "clostridium-perfringens-food-poisoning": "#b8874f",
    "staphylococcal-food-poisoning": "#c08a5d",
    "naegleria-fowleri-infection": "#5a5f9f",
    "parvovirus-b19-infection": "#b89f74",
    "human-metapneumovirus-infection": "#9fb2c3",
    "powassan-virus-disease": "#5f6394",
    "colorado-tick-fever": "#b67e55",
    "bourbon-virus-disease": "#a56f5e",
    "heartland-virus-disease": "#8f8f5c",
    "cytomegalovirus-infection": "#9d7ea9",
    "epstein-barr-virus-infection": "#8f77a8",
    "cryptococcosis": "#707392",
    "mucormycosis": "#8a765f",
    "pinworm-infection": "#b3a15f",
    "trichomoniasis": "#8f8ab8",
    "creutzfeldt-jakob-disease": "#777777",
    "ringworm": "#9a8758",
    "molluscum-contagiosum": "#b4808b",
    "trachoma": "#b49b5a",
    "yaws": "#aa7458",
    "buruli-ulcer": "#6f7295",
    "cystoisosporiasis": "#7478a5",
    "capnocytophaga-infection": "#a17d63",
    "acanthamoeba-keratitis": "#5f65a5",
    "balamuthia-mandrillaris-infection": "#8f8060",
    "blastocystis-infection": "#74789f",
    "angiostrongyliasis": "#b4935d",
    "gnathostomiasis": "#a87856",
    "talaromycosis": "#66698f",
    "chromoblastomycosis": "#9b7a58",
    "noma": "#8b735f",
    "jamestown-canyon-virus-disease": "#6a6ea0",
    "bartonella-henselae-infection": "#a67c5b",
    "cronobacter-infection": "#c29a55",
    "sarcocystosis": "#6f73a5",
    "fasciolopsiasis": "#6f739b",
    "chancroid": "#b16d62",
    "lymphogranuloma-venereum": "#9d6f8f",
    "donovanosis": "#a06f62",
    "mycoplasma-genitalium-infection": "#b0777d",
    "mycetoma": "#9f8c5f",
    "sars": "#8ca7bd",
    "trichuriasis": "#9b8d57",
    "pneumocystis-pneumonia": "#7f82a1",
    "taeniasis": "#a88f57",
    "opisthorchiasis": "#646899",
    "tungiasis": "#b58a4f",
    "hendra-virus-disease": "#8a7b55",
    "herpes-b-virus-infection": "#9b7aa5",
    "orf-virus-infection": "#a78657",
    "chapare-hemorrhagic-fever": "#a65454",
    "nontuberculous-mycobacterial-disease": "#6f7293",
    "elizabethkingia-infection": "#707392",
    "klebsiella-infection": "#a27d72",
    "esbl-producing-enterobacterales-infection": "#7a748f",
    "non-polio-enterovirus-infection": "#8aa7c2",
    "common-cold": "#9fb8c9",
    "bacterial-vaginosis": "#b0798f",
    "southern-tick-associated-rash-illness": "#61669b",
    "head-lice-infestation": "#9a8b63",
    "pubic-lice-infestation": "#a07b66",
    "body-lice-infestation": "#8b765b",
    "myiasis": "#b78b53",
    "herpes-simplex-virus-infection": "#a86f93",
    "human-t-lymphotropic-virus-1-infection": "#8c6fa7",
    "shingles": "#9b7ab0",
    "conjunctivitis": "#8f91a8",
    "meningitis": "#8c9ab8",
    "impetigo": "#b18463",
    "cellulitis": "#a9786b",
    "necrotizing-fasciitis": "#9c5f5f",
    "helicobacter-pylori-infection": "#a98f55",
    "tinea-pedis": "#6a6e9c",
    "vulvovaginal-candidiasis": "#b28aa0",
    "nocardiosis": "#8a8264",
    "paracoccidioidomycosis": "#8f765c",
    "acute-flaccid-myelitis": "#7f8faa",
    "pneumonia": "#9bb0c2",
    "sinusitis": "#9ea1bd",
    "acute-bronchitis": "#8faec0",
    "otitis-media": "#b0a071",
    "urinary-tract-infection": "#75778f",
    "infectious-gastroenteritis": "#6a6fa6",
}
PATHOGEN_ATLAS_CATEGORIES = {
    "yellow-fever": ("mosquito-borne", "Mosquito-borne / arboviral"),
    "cholera": ("fecal-oral-waterborne", "Fecal-oral / waterborne"),
    "measles": ("airborne-respiratory", "Airborne / respiratory"),
    "mpox": ("contact-sexual-bloodborne", "Contact, sexual, or bloodborne"),
    "avian-influenza-h5n1": (
        "zoonotic-animal-interface",
        "Zoonotic / animal interface",
    ),
    "hantavirus": ("rodent-environmental", "Rodent-borne / environmental"),
    "dengue": ("mosquito-borne", "Mosquito-borne / arboviral"),
    "malaria": ("mosquito-borne", "Mosquito-borne / parasitic"),
    "tuberculosis": ("airborne-respiratory", "Airborne / respiratory"),
    "plague": ("flea-louse-mite-borne", "Flea, louse, and mite-borne"),
    "zika-virus-disease": ("mosquito-borne", "Mosquito-borne / arboviral"),
    "chikungunya": ("mosquito-borne", "Mosquito-borne / arboviral"),
    "west-nile-virus": ("mosquito-borne", "Mosquito-borne / arboviral"),
    "japanese-encephalitis": ("mosquito-borne", "Mosquito-borne / arboviral"),
    "poliomyelitis": ("fecal-oral-waterborne", "Fecal-oral / waterborne"),
    "hepatitis-a": ("fecal-oral-waterborne", "Fecal-oral / waterborne"),
    "typhoid-fever": ("fecal-oral-waterborne", "Fecal-oral / waterborne"),
    "norovirus": ("fecal-oral-waterborne", "Fecal-oral / waterborne"),
    "smallpox": ("airborne-respiratory", "Airborne / respiratory"),
    "seasonal-influenza": ("airborne-respiratory", "Airborne / respiratory"),
    "covid-19": ("airborne-respiratory", "Airborne / respiratory"),
    "diphtheria": ("airborne-respiratory", "Airborne / respiratory"),
    "pertussis": ("airborne-respiratory", "Airborne / respiratory"),
    "ebola-virus-disease": ("zoonotic-animal-interface", "Zoonotic / animal interface"),
    "marburg-virus-disease": (
        "zoonotic-animal-interface",
        "Zoonotic / animal interface",
    ),
    "nipah-virus-disease": ("zoonotic-animal-interface", "Zoonotic / animal interface"),
    "rabies": ("zoonotic-animal-interface", "Zoonotic / animal interface"),
    "anthrax": ("zoonotic-animal-interface", "Zoonotic / animal interface"),
    "mers": ("zoonotic-animal-interface", "Zoonotic / animal interface"),
    "lassa-fever": ("rodent-environmental", "Rodent-borne / environmental"),
}
PATHOGEN_ATLAS_CATEGORY_ALIASES = {
    "fecal-oral": ("fecal-oral-waterborne", "Fecal-oral / waterborne"),
    "contact-sexual": ("contact-sexual-bloodborne", "Contact, sexual, or bloodborne"),
    "zoonotic-vector": ("flea-louse-mite-borne", "Flea, louse, and mite-borne"),
    "other": ("other-mixed", "Other / mixed transmission"),
}
PATHOGEN_STATUS_LABELS = {
    "consensus": "Consensus",
    "mixed": "Mixed / debated",
    "contested": "Contested",
    "weak": "Weakly supported",
}
PATHOGEN_WRITING_LABELS = {
    "direct": "Written here directly",
    "adjacent": "Adjacent writing",
    "not_yet_written": "No dedicated post yet",
}
PUBLIC_COPY_REPLACEMENTS = {
    "Mpox belongs in the atlas because it combines a geographically anchored Central/West African history with abrupt export through wildlife trade and then a very different twenty-first century global transmission pattern.": "Mpox combines a geographically anchored Central and West African history with wildlife-trade export events and a distinct twenty-first-century pattern of networked global transmission.",
    "It forces the site to distinguish clades, transport mode, and transmission network rather than collapsing everything into one map pin.": "Mpox geography separates clades, transport events, animal reservoirs, and transmission networks instead of collapsing them into a single point of origin.",
    "H5N1 belongs in the atlas because its contemporary geography is not a human epidemic map first; it is a bird-route, farm-system, and spillover map whose human layer remains contingent.": "H5N1 is not primarily a human epidemic map. Its geography follows bird migration, poultry systems, mammal spillover, dairy-herd events, and occupational exposure.",
    "It creates a genuinely different map grammar from the classic human-to-human pathogens and foregrounds One Health risk.": "The spatial problem is One Health risk: animal movement, farm systems, and spillover opportunities before sustained human-to-human transmission.",
    "It lets the atlas show how a pathogen can move with people, water storage, ships, and vector habitat rather than by human travel alone.": "Yellow fever moves with people, water storage, ships, and vector habitat, not by human travel alone.",
    "It forces the atlas to behave like an encyclopedia rather than a single-route animation and keeps us honest about host ecology, geography, and syndrome differences.": "Hantavirus geography follows rodent-host biogeography, ecological exposure settings, and the split between Old World hemorrhagic-fever viruses and New World cardiopulmonary viruses.",
    "Hantaviruses belong in the atlas because they break the habit of pretending every pathogen has one clean human-travel route. The real map is rodent-host biogeography, ecological exposure settings, and the split between Old World hemorrhagic-fever viruses and New World cardiopulmonary viruses.": "Hantavirus geography follows rodent-host biogeography, ecological exposure settings, and the split between Old World hemorrhagic-fever viruses and New World cardiopulmonary viruses.",
    "It turns the atlas toward contemporary global change instead of leaving it stranded in historical imperial routes.": "Dengue shows how urbanization, climate, vector range, water storage, travel, and surveillance reshape disease geography in real time.",
    "Malaria belongs in the atlas because it shows how vector ecology, land use, labor systems, altitude, war, and climate can redraw disease geography across centuries without one neat origin story doing all the work.": "Malaria shows how vector ecology, land use, labor systems, altitude, war, and climate can redraw disease geography across centuries without a single tidy origin story.",
    "It keeps the atlas from becoming virus-only and forces a map grammar built around mosquitoes, species differences, and ecological receptivity.": "Its geography is built around mosquitoes, parasite species, ecological receptivity, control programs, and uneven health-system reach.",
    "Tuberculosis belongs in the atlas because it is both ancient and modern at once: a human co-traveler that thrives in crowding, poverty, institutional confinement, and uneven public health capacity.": "Tuberculosis is ancient and modern at once: a human co-traveler that thrives in crowding, poverty, institutional confinement, migration, HIV, and uneven public-health capacity.",
    "It turns the atlas toward chronic structural transmission instead of one spectacular frontier jump.": "Its map is chronic and structural: airborne transmission shaped by housing, labor, prisons, care access, and drug-resistance systems.",
    "Plague belongs in the atlas because it is one of the clearest historical demonstrations that reservoir ecology, trade corridors, warfare, and maritime ports can repeatedly rewire a continent.": "Plague is one of the clearest historical demonstrations that reservoir ecology, trade corridors, warfare, and maritime ports can repeatedly rewire a continent.",
    "It lets the atlas bridge deep historical fear, genomic reconstruction, and the very practical map logic of rodents, fleas, and ports.": "Plague links deep historical fear, genomic reconstruction, and the practical geography of rodents, fleas, and ports.",
    "Measles is a useful atlas pathogen because its deeper origin story is partly reconstructed from molecular-clock work, while its colonial spread story is brutally visible in the Americas and Pacific.": "Measles has a partly reconstructed deeper origin story from molecular-clock work, while its colonial spread is brutally visible in the Americas and Pacific.",
    "A durable desk file generated from the active dossier story cluster.": "A durable desk file assembled from current reporting, official updates, and source clusters.",
    "Summary stays within source text and metadata; no outside facts were added.": "The summary stays close to the source language and should be read as an initial source note, not a final interpretation.",
    "summary stays within source text and metadata; no outside facts were added.": "the summary stays close to the source language and should be read as an initial source note, not a final interpretation.",
    "Limited detail was available from feed metadata alone.": "Only a brief source description was available at publication time.",
    "limited detail was available from feed metadata alone.": "only a brief source description was available at publication time.",
    "metadata_only_signal": "brief_source_signal",
    "metadata_only": "brief_source",
    "metadata-only signal": "brief source signal",
    "Metadata-only signal": "Brief source signal",
    "metadata-only follow-ups": "brief-source follow-ups",
    "Metadata-only follow-ups": "Brief-source follow-ups",
    "Metadata-only": "Brief source",
    "metadata only": "brief source",
    "Metadata only": "Brief source",
    "Live fetches": "Current source checks",
    "Live fetch": "Current source",
    "live fetch": "current source",
    "Wrapper-only": "Source-link only",
    "wrapper-only": "source-link only",
    "wrapper only": "source-link only",
    "Wrapper only": "Source-link only",
}
